### ISSUE TITLE
Change Setting

### ISSUE THREAD

**Issue by 223n** [223n/certcheck#4]
## 内容

設定ファイルの構成を以下のようにしてみてはどうか？

```yaml
targets:
  - name: (分かりやすい名称)
    endpoint: (調べるURL)
    threshold: (slackに通知する残日数)
  - name: (分かりやすい名称)
    endpoint: (調べるURL)
    threshold: (slackに通知する残日数)
    # Slackの通知先を上書き
    hook_url: (slackの Incomming WebHooks で発行した Webhook URL)
    channel: (チャンネル)
    username: (slackの通知で表示するユーザ名)
    icon: (アイコン)

slack:
  hook_url: (slackの Incomming WebHooks で発行した Webhook URL)
  channel: (チャンネル)
  username: (slackの通知で表示するユーザ名)
  icon: (アイコン)
```

## 理由

デフォルトのSlack通知先を１つ設定した後、必要に応じて上書きする運用が可能になる。
